version: "3.8"

networks:
  wordpress:

services:
  # Application
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress

  # Database Server
  mysql:
    image: mysql:5.7.38
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      # automatically creates database and user
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress

  # Database GUI Server
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8001:80
    depends_on:
      - mysql
    environment:
      # automatically logs in given user
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - wordpress
